
## <span style="color:red;">The output bed is not sorted properly. So SORT the bed output<span style="color:red;">.

In [1]:
import pandas as pd 
import pandas as pd
import os



# Define input and output file paths
input_file = "../Reference_like_Data/Ensembl/mart_export.txt"
output_file = os.path.dirname(input_file)+"/Ensemble_unique_ProteinCodig_genes"

protin_file = '../Reference_like_Data/protein_coding_gene.txt'

# Read data into a pandas DataFrame
df = pd.read_csv(input_file, sep='\t', low_memory=False)
df.head()

,Chromosome/scaffold name,Gene start (bp),Gene end (bp),Gene name,Transcription start site (TSS),Transcript start (bp),Transcript end (bp),Strand
0,MT,577,647,MT-TF,577,577,647,1
1,MT,648,1601,MT-RNR1,648,648,1601,1
2,MT,1602,1670,MT-TV,1602,1602,1670,1
3,MT,1671,3229,MT-RNR2,1671,1671,3229,1
4,MT,3230,3304,MT-TL1,3230,3230,3304,1

In [2]:
# Filter genes based on chromosome
valid_chromosomes = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']
df = df[df['Chromosome/scaffold name'].isin(valid_chromosomes)]

In [3]:
df['Gene Length (bp)'] = abs(df['Gene end (bp)'] - df['Gene start (bp)'])

In [4]:
# Sort by gene length in descending order and drop duplicates keeping the longest gene
df = df.sort_values(by='Gene Length (bp)', ascending=False).drop_duplicates(subset='Gene name')

In [5]:
# Add 'chr' to the 'Chromosome/scaffold name' column
df['Chromosome/scaffold name'] = 'chr' + df['Chromosome/scaffold name'].astype(str)
df.head()

,Chromosome/scaffold name,Gene start (bp),Gene end (bp),Gene name,Transcription start site (TSS),Transcript start (bp),Transcript end (bp),Strand,Gene Length (bp)
211376,chr16,5239802,7713340,RBFOX1,7664764,7664764,7710844,1,2473538
123082,chr7,146116002,148420998,CNTNAP2,147638809,147638809,148415779,1,2304996
134664,chr9,8314246,10613002,PTPRD,8733894,8317405,8733894,-1,2298756
150495,chrX,31097677,33339609,DMD,31266967,31126886,31266967,-1,2241932
248402,chr11,83455012,85628335,DLG2,85627749,85598657,85627749,-1,2173323

In [6]:
protein_df = pd.read_csv(protin_file,sep='\t',low_memory=False)
protein_df.head()

,hgnc_id,symbol,name,locus_group,locus_type,status,location,location_sortable,alias_symbol,alias_name,...,cd,lncrnadb,enzyme_id,intermediate_filament_db,rna_central_ids,lncipedia,gtrnadb,agr,mane_select,gencc
0,HGNC:5,A1BG,alpha-1-B glycoprotein,protein-coding gene,gene with protein product,Approved,19q13.43,19q13.43,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGNC:5,ENST00000263100.8|NM_130786.4,NaN
1,HGNC:24086,A1CF,APOBEC1 complementation factor,protein-coding gene,gene with protein product,Approved,10q11.23,10q11.23,ACF|ASP|ACF64|ACF65|APOBEC1CF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGNC:24086,ENST00000373997.8|NM_014576.4,NaN
2,HGNC:7,A2M,alpha-2-macroglobulin,protein-coding gene,gene with protein product,Approved,12p13.31,12p13.31,FWP007|S863-7|CPAMD5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGNC:7,ENST00000318602.12|NM_000014.6,HGNC:7
3,HGNC:23336,A2ML1,alpha-2-macroglobulin like 1,protein-coding gene,gene with protein product,Approved,12p13.31,12p13.31,FLJ25179|p170,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGNC:23336,ENST00000299698.12|NM_144670.6,HGNC:23336
4,HGNC:30005,A3GALT2,"alpha 1,3-galactosyltransferase 2",protein-coding gene,gene with protein product,Approved,1p35.1,01p35.1,IGBS3S|IGB3S,iGb3 synthase|isoglobotriaosylceramide synthase,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGNC:30005,ENST00000442999.3|NM_001080438.1,NaN

In [7]:
protein_df_symbol = set(protein_df['symbol'].tolist())
len(protein_df_symbol)

19237

In [8]:
protein_gene = df[df['Gene name'].isin(protein_df_symbol)]
print(protein_gene.shape)
protein_gene.head()

(19182, 9)

,Chromosome/scaffold name,Gene start (bp),Gene end (bp),Gene name,Transcription start site (TSS),Transcript start (bp),Transcript end (bp),Strand,Gene Length (bp)
211376,chr16,5239802,7713340,RBFOX1,7664764,7664764,7710844,1,2473538
123082,chr7,146116002,148420998,CNTNAP2,147638809,147638809,148415779,1,2304996
134664,chr9,8314246,10613002,PTPRD,8733894,8317405,8733894,-1,2298756
150495,chrX,31097677,33339609,DMD,31266967,31126886,31266967,-1,2241932
248402,chr11,83455012,85628335,DLG2,85627749,85598657,85627749,-1,2173323

In [9]:
bedlike = protein_gene[['Chromosome/scaffold name', 'Gene start (bp)','Gene end (bp)','Gene name']]
bedlike.head()

       Chromosome/scaffold name  Gene start (bp)  Gene end (bp) Gene name
211376                    chr16          5239802        7713340    RBFOX1
123082                     chr7        146116002      148420998   CNTNAP2
134664                     chr9          8314246       10613002     PTPRD
150495                     chrX         31097677       33339609       DMD
248402                    chr11         83455012       85628335      DLG2

In [10]:
bedlike.to_csv(output_file+".bed", sep='\t', header=False, index=False)