In [1]:
import pandas as pd
allgenes_file = '../Reference_like_Data/All_Gene_Info.txt_prom1000_sorted.txt_expnaded.txt_sorted.txt'
outname= '../Reference_like_Data/ProteinCodingPromoterExpanded.txt'
allgenes_df = pd.read_csv(allgenes_file, sep='\t', header=None)
protin_file = '../Reference_like_Data/protein_coding_gene.txt'

In [2]:
protein_df = pd.read_csv(protin_file,sep='\t',low_memory=False)
protein_df.head()

,hgnc_id,symbol,name,locus_group,locus_type,status,location,location_sortable,alias_symbol,alias_name,...,cd,lncrnadb,enzyme_id,intermediate_filament_db,rna_central_ids,lncipedia,gtrnadb,agr,mane_select,gencc
0,HGNC:5,A1BG,alpha-1-B glycoprotein,protein-coding gene,gene with protein product,Approved,19q13.43,19q13.43,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGNC:5,ENST00000263100.8|NM_130786.4,NaN
1,HGNC:24086,A1CF,APOBEC1 complementation factor,protein-coding gene,gene with protein product,Approved,10q11.23,10q11.23,ACF|ASP|ACF64|ACF65|APOBEC1CF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGNC:24086,ENST00000373997.8|NM_014576.4,NaN
2,HGNC:7,A2M,alpha-2-macroglobulin,protein-coding gene,gene with protein product,Approved,12p13.31,12p13.31,FWP007|S863-7|CPAMD5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGNC:7,ENST00000318602.12|NM_000014.6,HGNC:7
3,HGNC:23336,A2ML1,alpha-2-macroglobulin like 1,protein-coding gene,gene with protein product,Approved,12p13.31,12p13.31,FLJ25179|p170,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGNC:23336,ENST00000299698.12|NM_144670.6,HGNC:23336
4,HGNC:30005,A3GALT2,"alpha 1,3-galactosyltransferase 2",protein-coding gene,gene with protein product,Approved,1p35.1,01p35.1,IGBS3S|IGB3S,iGb3 synthase|isoglobotriaosylceramide synthase,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGNC:30005,ENST00000442999.3|NM_001080438.1,NaN

In [3]:
protein_df_symbol = set(protein_df['symbol'].tolist())
len(protein_df_symbol)

19237

In [4]:
allgenes_df.head()

      0      1      2            3
0  chr1   9873  12873      DDX11L1
1  chr1  16436  19436    MIR6859-1
2  chr1  27925  30925  MIR1302-2HG
3  chr1  28365  31365    MIR1302-2
4  chr1  28370  31370       WASH7P

In [5]:
outdf = allgenes_df[allgenes_df[3].isin(protein_df_symbol)]
outdf.head()

       0       1       2       3
6   chr1   67090   70090   OR4F5
29  chr1  450678  453678  OR4F29
35  chr1  685654  688654  OR4F16
36  chr1  697925  700925  OR4F16
37  chr1  710799  713799  OR4F16

In [6]:
outdf.to_csv(outname,sep='\t',index=False, header= False)